table BQKMonthlyReport
	lineageTag: 4d517241-a0e5-4de9-a9a7-c3e7628a0296

	column 'Reporting Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7a07824-3a87-4969-96d4-e79746e5b6aa
		summarizeBy: none
		sourceColumn: Reporting Date

		variation Variation
			isDefault
			relationship: ef7b1497-f8ab-4802-b8f8-9024d36cda70
			defaultHierarchy: LocalDateTable_95b0dd97-898e-45d3-ae56-fa117db654ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Financial Institution'
		dataType: string
		lineageTag: 96a1093c-7f39-4bca-878c-5681b1af3a53
		summarizeBy: none
		sourceColumn: Financial Institution

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 793303c9-ac0b-4c55-965e-260e3a8838fe
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: 1a7a5acf-4376-47e8-acd4-d1abc46ef4fc
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column SubSubCategory
		dataType: string
		lineageTag: 0148ea03-2d19-4e48-b8b3-ad3eaf731d89
		summarizeBy: none
		sourceColumn: SubSubCategory

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 4b581272-092a-46f8-bafc-ed6ef56a44ff
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition BQKMonthlyReport = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Donika Mjeku\Desktop\BQK_Module\BQK_Module.xlsx"), null, true),
				    BQKMonthlyReport_Sheet = Source{[Item="BQKMonthlyReport",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(BQKMonthlyReport_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Reporting Date", type date}, {"Financial Institution", type text}, {"Category", type text}, {"SubCategory", type text}, {"SubSubCategory", type text}, {"Value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

